apiVersion: v1
kind: Service
metadata:
  name: my-lb
  labels:
    app: test-api
  namespace: web-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: test-api